apiVersion: v1
kind: Service
metadata:
  name: {{ include "crewlink.fullname" . }}
  labels:
    {{- include "crewlink.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: 80
      targetPort: 9736
      protocol: TCP
      name: http
  selector: {{- include "crewlink.selectorLabels" . | nindent 4 }}
